project:
  type: website
  output-dir: docs

website:
  title: "Documentos Reproducibles con Rmarkdown"
  sidebar:
    sytle: "docked"
    pinned: true
    alignment: center
    tools:
      - icon: github
        href: https://github.com/ajpelu/quarto-course-website-template
        text: GitHub
    contents: 
      - href: index.qmd
        text: Documentos Reproducibles 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

